name: CI

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - "scripts/**"
      - "rockspecs/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "scripts/**"
      - "rockspecs/**"
      - ".github/workflows/ci.yml"

jobs:
  test-unix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        lua-version: ["5.1", "5.2", "5.3", "5.4", "5.5", "luajit"]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v6

      - uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: ${{ matrix.lua-version }}

      - uses: leafo/gh-actions-luarocks@v6

      - name: Build
        run: luarocks make rockspecs/timeutil-scm-1.rockspec

      - name: Test
        run: lua tests/timeutil.test.lua

  test-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: msvc
            lua-version: "5.1"
          - toolchain: msvc
            lua-version: "5.2"
          - toolchain: msvc
            lua-version: "5.3"
          - toolchain: msvc
            lua-version: "5.4"
          - toolchain: msvc
            lua-version: "5.5"
          - toolchain: mingw
            lua-version: "luajit"

    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v6

      - if: ${{ matrix.toolchain == 'msvc' }}
        uses: ilammy/msvc-dev-cmd@v1

      - uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: ${{ matrix.lua-version }}

      - uses: leafo/gh-actions-luarocks@v6

      - name: Build
        run: luarocks make rockspecs/timeutil-scm-1.rockspec

      - name: Test
        run: lua tests/timeutil.test.lua
